### ISSUE TITLE
Templating inside secondary info?

### ISSUE THREAD

**Issue by undert03** [MizterB/lovelace-secondaryinfo-entity-row#3]
any way to templating in it ie

secondary_info: "[[ {{sensor.cmd_nicehash_usdbtc.state|float * sensor.cmd_nicehash_wallet.state|float} }]]"

**Comment by MizterB** [comment]
Unfortunately, not right now.  The current templating capabilities are documented on the [card-tools](https://github.com/thomasloven/lovelace-card-tools) GitHub page.  If you are interested in additional capabilities, I would suggest submitting a feature request over there.
