### ISSUE TITLE
Uncaught error: cannot read querySelector

### ISSUE THREAD

**Issue by chemelli74** [MizterB/lovelace-secondaryinfo-entity-row#49]
Hi,

noticed this error in my browser debug page:

![image](https://user-images.githubusercontent.com/57354320/184480317-cc949c95-6385-403d-9692-bb5d9c2de44d.png)

Apparently everything still work fine .

Simone

**Comment by ildar170975** [comment]
Confirmed
Same as https://github.com/custom-cards/secondaryinfo-entity-row/issues/40

**Comment by chemelli74** [comment]
Close as duplicate.

Simone
